#!/bin/bash
mysql -u root -ptoor -e 'insert into fakealert values(1, 2, 3)' niddcore
mysql -u root -ptoor -e 'insert into fakealert values(3, 4, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(3, 4, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(2, 3, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 1, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 1, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 1, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(1, 3, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(2, 3, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 1, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(1, 3, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(3, 8, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(3, 8, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(3, 8, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(2, 2, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 1, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(0, 9, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(5, 4, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(5, 4, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(5, 4, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 8, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(1, 9, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(2, 3, 3)' niddcore
#mysql -u root -ptoor -e 'insert into fakealert values(4, 2, 3)' niddcore
